### ISSUE TITLE
What alternatives are there to using CREST APIs?

### ISSUE THREAD

**Issue by ugreg** [PartnerCenterSamples/Commerce-API-DotNet#5]

**Comment by RaedJarrar** [comment]
Definitely! CREST is on the way of getting retired and is being replaced by the Partner Center API/SDK. The new Partner Center API provides a simpler, more consistent and more comprehensive set of scenarios than CREST. You can find the documentation at: https://msdn.microsoft.com/en-us/library/partnercenter/mt634708.aspx

We have a .NET SDK which makes accessing the APIs much easier in case your platform was .NET: https://www.nuget.org/packages/Microsoft.Store.PartnerCenter/

We also are releasing a Java SDK very soon. Hope this helps.

**Comment by ugreg** [comment]
More then helpful! Exactly what I needed for the partner I'm working with (I am a field TE in USDX stationed in the San Francisco Bay Area for context). Thanks for the quick follow up Raed. going to connect with my partner on this now!
